# Generated by Django 4.2 on 2023-06-07 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0002_remove_plan_plan_snack_lunch_dinner_breakfast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='lunch',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='completed_day',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='days_of_week',
        ),
        migrations.AddField(
            model_name='plan',
            name='breakfast',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='dinner',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='lunch',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='plan',
            name='snacks',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Breakfast',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
    ]
