# Generated by Django 4.2 on 2023-06-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_theday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TheDay',
        ),
    ]
