# Generated by Django 4.2 on 2023-06-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0005_delete_theday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='lunch',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='snacks',
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(default='')),
                ('fat', models.PositiveIntegerField()),
                ('protein', models.PositiveIntegerField()),
                ('carbohydrates', models.PositiveIntegerField()),
                ('plan', models.ManyToManyField(to='meal_plans.plan')),
            ],
        ),
    ]
