# Generated by Django 4.2 on 2023-06-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0006_remove_plan_breakfast_remove_plan_dinner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='plan',
        ),
        migrations.AddField(
            model_name='plan',
            name='food_items',
            field=models.ManyToManyField(to='meal_plans.fooditem'),
        ),
    ]
