# Generated by Django 4.2 on 2023-06-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0007_remove_fooditem_plan_plan_food_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrates',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
