# Generated by Django 4.2.5 on 2024-03-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0010_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
